### ISSUE TITLE
big todo list

### ISSUE THREAD

**Issue by machty** [machty/ember-constraint-router#1]
- [ ] it should be possible to invalidate a `match` and let the nav stack determine how to "fix" / redirect / etc
- [ ] build out a few example apps in the `tests/`
  - deli ordering app
  - twitter clone
  - ember-rideshare
- [ ] flesh out the story for loading states and how to opt into handling loading states in the component
- [ ] flesh out _what_ a scoped service is
  - is it a Route object tied to a particular version of the model? or do you need pass the model into various actions for content?
- [ ] introduce lifespan concept: frame components can be re-rendered simultaneously, so they need some kind of mechanism to know when they're rendered (and allow for a transition `t` parameter to be passed in as well)
- [ ] how does bird's eye view debugging "play" with outlets/headers/footers etc?

**Comment by machty** [comment]
taking things in a bit of different direction, a lot of these no longer make sense
